{{- with .Values.deployment }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app.kubernetes.io/component: auth
    app.kubernetes.io/name: auth
#    app.kubernetes.io/part-of: greeter
spec:
  replicas: {{ .replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: auth
  template:
    metadata:
      labels:
        app.kubernetes.io/component: auth
        app.kubernetes.io/name: auth
#        app.kubernetes.io/part-of: greeter
    spec:
      {{- if and $.Values.serviceAccount.create }}
      serviceAccountName: {{ $.Values.serviceAccount.name }}
      {{- end }}
      {{- if .pullSecrets }}
      imagePullSecrets:
      {{- range .pullSecrets }}
      - name: {{ . }}
      {{- end }}
      {{- end }}
      containers:
      - name: auth
        image: "{{ .image.repository }}:{{ .image.tag | default $.Chart.AppVersion }}"
        imagePullPolicy: {{ .image.pullPolicy }}
        ports:
        - containerPort: 8080
        # TODO Make this configurable together with a debug-capable image
        # Remote debug port
        - containerPort: 40000
        env:
        - name: HTTP_PORT
          value: "8080"
        - name: REDIS_ADDR
          value: {{ $.Values.redis.addr }}
        - name: REDIS_CREDS
          value: {{ $.Values.redis.credsFile }}
        - name: DB_ADDR
          value: {{ $.Values.db.addr}}
        - name: DB_CREDS
          value: {{ $.Values.db.credsFile }}
        - name: AUTH_TOKEN_CREDS
          value: {{ $.Values.auth.credsFile }}
        {{- if .volumeMounts }}
        volumeMounts:
        {{- .volumeMounts | toYaml | nindent 8 }}
        {{- end }}
      {{- if .volumes }}
      volumes:
      {{- .volumes | toYaml | nindent 6 }}
      {{- end }}
{{- end }}
