deployment:
  replicaCount: 1
  image:
    repository: toboregistry.azurecr.io/example-services/greeter-ui
    pullPolicy: IfNotPresent
#    tag: 1.0.0
  pullSecrets: []

serviceAccount:
  create: false
  # name: greeter-ui-service-account
  # annotations: {}

service:
  type: ClusterIP
  annotations: {}

ingress:
  create: false
  # annotations:
  #   kubernetes.io/ingress.class: nginx
  # paths:
  # - path: "/greeter(/|$)(.*)"
