Http:
  Port: 8080
  CertFile: /var/secrets/ca.crt

Db:
  Dsn: mysql://{{ .User }}:{{ .Password }}@tcp({{ .Endpoint }})/{{ .Name }}
  # User: ""
  # Password: ""
  # Endpoint: ""
  Name: login
DbConfigDir: /var/secrets/db

Redis:
  Dsn: redis://{{ .Endpoint }}
  # Dsn: redis://{{ .User }}:{{ .Password }}@{{ .Endpoint }}/{{ .Db }}
  # User: ""
  # Password: ""
  # Endpoint: ""
  # Db: 0
  TLS: false
RedisConfigDir: /var/secrets/redis

AccessTokenConfigDir: /var/secrets/at
