Http:
  Port: 8080
  CertFile: /var/secrets/ca.crt

# Azure
#Db:
#  Dsn: "tcp({{ .Endpoint }})/{{ .Name }}"
#  Driver: "mysqlMsi"
#  # Endpoint: ""
#  Name: login

Db:
  Dsn: "{{ .User }}:{{ .Password }}@tcp({{ .Endpoint }})/{{ .Name }}"
  Driver: "mysql"
  # User: ""
  # Password: ""
  # Endpoint: ""
  Name: login
DbConfigDir: /var/secrets/db

Redis:
  Dsn: "redis://{{ .Endpoint }}"
  # Dsn: redis://{{ .User }}:{{ .Password }}@{{ .Endpoint }}/{{ .Db }}
  # User: ""
  # Password: ""
  # Endpoint: ""
  # Db: 0
  TLS: false
RedisConfigDir: /var/secrets/redis

AccessTokenConfigDir: /var/secrets/at
