#
# Builder
#
FROM example-services/builder:latest AS builder

# 
# Runtime
#
FROM example-services/base-debug:latest

COPY config.yaml /usr/bin

ENV HTTP_PORT="8080" \
    CONFIG_FILE=/usr/bin/config.yaml

EXPOSE 8080
