deployment:
  replicaCount: 1
  image:
    repository: toboregistry.azurecr.io/example-services/login
    pullPolicy: IfNotPresent
#    tag: 1.0.0
  pullSecrets: []
  volumes: []
  volumeMounts: []

serviceAccount:
  create: false
  # name: auth-service-account
  # annotations: {}

service:
  type: ClusterIP
  annotations: {}

ingress:
  create: false
  # annotations:
  #   kubernetes.io/ingress.class: nginx,
  #   nginx.ingress.kubernetes.io/rewrite-target: /$2
  # paths:
  # - path: "/greeter/auth(/|$)(.*)"


redis:
  addr: ""
  credsFile: "/secrets/redis/redis-creds.json"

db:
  addr: ""
  credsFile: "/secrets/db/db-creds.json"

auth:
  credsFile: "/secrets/auth/auth-token-creds.json"
