deployment:
  replicaCount: 1
  image:
    repository: toboregistry.azurecr.io/example-services/greeter
    tag: 1.0.0
    pullPolicy: IfNotPresent
  pullSecrets: []
  volumes: []
  volumeMounts: []
  env: []

serviceAccount:
  create: false
  # name: messages-service-account
  # annotations: {}

service:
  type: ClusterIP
  annotations: {}

ingress:
  create: false
  # annotations:
  #   kubernetes.io/ingress.class: nginx
  #   nginx.ingress.kubernetes.io/rewrite-target: /$2
  # host: example.org
  # tlsSecret: example-org-secret
  # paths:
  # - path: "/greeter/auth(/|$)(.*)"

redis:
  endpoint: ""

db:
  endpoint: ""
