apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app.kubernetes.io/component: auth
    app.kubernetes.io/name: auth
    app.kubernetes.io/part-of: greeter
spec:
  replicas: {{ .Values.auth.replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: auth
  template:
    metadata:
      labels:
        app.kubernetes.io/component: auth
        app.kubernetes.io/name: auth
        app.kubernetes.io/part-of: greeter
    spec:
      containers:
      - name: auth
        image: "{{ .Values.auth.image.repository }}:{{ .Values.auth.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.auth.image.pullPolicy }}
        ports:
        - containerPort: 8080
        # Remote debug port
        - containerPort: 40000
        env:
        - name: HTTP_PORT
          value: "8080"
        - name: REDIS_DSN
          value: "redis-service:6379"
        - name: ACCESS_TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-token-secret
              key: ACCESS_TOKEN_SECRET
        - name: ACCESS_TOKEN_EXPIRY
          valueFrom:
            secretKeyRef:
              name: auth-token-secret
              key: ACCESS_TOKEN_EXPIRY
        - name: REFRESH_TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-token-secret
              key: REFRESH_TOKEN_SECRET
        - name: REFRESH_TOKEN_EXPIRY
          valueFrom:
            secretKeyRef:
              name: auth-token-secret
              key: REFRESH_TOKEN_EXPIRY
