apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app.kubernetes.io/component: auth
    app.kubernetes.io/name: auth
    app.kubernetes.io/part-of: greeter
spec:
  replicas: {{ .Values.auth.replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: auth
  template:
    metadata:
      labels:
        app.kubernetes.io/component: auth
        app.kubernetes.io/name: auth
        app.kubernetes.io/part-of: greeter
    spec:
      containers:
      - name: auth
        image: "{{ .Values.auth.image.repository }}:{{ .Values.auth.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.auth.image.pullPolicy }}
        ports:
        - containerPort: 8080
        # TODO Make this configurable together with a debug-capable image
        # Remote debug port
        - containerPort: 40000
        env:
        - name: HTTP_PORT
          value: "8080"
        - name: REDIS_ADDR
          value: {{ .Values.auth.redis.addr }}
        - name: DB_ADDR
          value: {{ .Values.auth.db.addr}}
        - name: DB_CREDS
          value: "/secrets/db/db-creds.json"
        - name: AUTH_TOKEN_CREDS
          value: "/secrets/auth/auth-token-creds.json"
        volumeMounts:
        {{- .Values.auth.volumeMounts | toYaml | nindent 8 }}
      volumes:
      {{- .Values.auth.volumes | toYaml | nindent 6 }}
