apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app.kubernetes.io/component: auth
    app.kubernetes.io/name: auth
    app.kubernetes.io/part-of: greeter
spec:
  replicas: {{ .Values.auth.replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: auth
  template:
    metadata:
      labels:
        app.kubernetes.io/component: auth
        app.kubernetes.io/name: auth
        app.kubernetes.io/part-of: greeter
    spec:
      containers:
      - name: auth
        image: "{{ .Values.auth.image.repository }}:{{ .Values.auth.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.auth.image.pullPolicy }}
        ports:
        - containerPort: 8080
        # TODO Make this configurable together with a debug-capable image
        # Remote debug port
        - containerPort: 40000
        env:
        - name: HTTP_PORT
          value: "8080"
        # TODO Load this from a ConfigMap?
        - name: REDIS_DSN
          value: {{ .Values.auth.redis }}
        - name: ACCESS_TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-token-secret
              key: ACCESS_TOKEN_SECRET
        - name: ACCESS_TOKEN_EXPIRY
          valueFrom:
            secretKeyRef:
              name: auth-token-secret
              key: ACCESS_TOKEN_EXPIRY
        - name: REFRESH_TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-token-secret
              key: REFRESH_TOKEN_SECRET
        - name: REFRESH_TOKEN_EXPIRY
          valueFrom:
            secretKeyRef:
              name: auth-token-secret
              key: REFRESH_TOKEN_EXPIRY
        # TODO Load this from a ConfigMap?
        - name: DB_ADDR
          value: {{ .Values.auth.db }}
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: auth-db-secret
              key: USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: auth-db-secret
              key: PASSWORD
