{{- with .Values.auth }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app.kubernetes.io/component: auth
    app.kubernetes.io/name: auth
    app.kubernetes.io/part-of: greeter
spec:
  replicas: {{ .replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: auth
  template:
    metadata:
      labels:
        app.kubernetes.io/component: auth
        app.kubernetes.io/name: auth
        app.kubernetes.io/part-of: greeter
    spec:
      containers:
      - name: auth
        image: "{{ .image.repository }}:{{ .image.tag | default $.Chart.AppVersion }}"
        imagePullPolicy: {{ .image.pullPolicy }}
        {{- if .image.pullSecrets }}
        imagePullSecrets:
        {{- range .image.pullSecrets }}
        - name: {{ . }}
        {{- end }}
        {{- end }}
        {{- if and .serviceAccount.name }}
        serviceAccountName: {{ .serviceAccount.name }}
        {{- end }}
        ports:
        - containerPort: 8080
        # TODO Make this configurable together with a debug-capable image
        # Remote debug port
        - containerPort: 40000
        env:
        - name: HTTP_PORT
          value: "8080"
        - name: REDIS_ADDR
          value: {{ .redis.addr }}
        - name: REDIS_CREDS
          value: {{ .redis.credsFile }}
        - name: DB_ADDR
          value: {{ .db.addr}}
        - name: DB_CREDS
          value: {{ .db.credsFile }}
        - name: AUTH_TOKEN_CREDS
          value: {{ .auth.credsFile }}
        {{- if .volumeMounts }}
        volumeMounts:
        {{- .volumeMounts | toYaml | nindent 8 }}
        {{- end }}
      {{- if .volumes }}
      volumes:
      {{- .volumes | toYaml | nindent 6 }}
      {{- end }}
{{- end }}
