{{- with .Values.auth.ingress -}}
{{- if .enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-ingress
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app.kubernetes.io/component: auth
    app.kubernetes.io/name: auth-ingress
    app.kubernetes.io/part-of: greeter
spec:
  rules:
    - http:
        paths:
          {{- range .paths }}
          - path: {{ . }}
            backend:
              serviceName: auth-service
              servicePort: 8080
          {{- end }}
{{- end }}
{{- end }}
