apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app.kubernetes.io/component: auth
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/part-of: greeter
spec:
  type: {{ .Values.auth.service.type | default "ClusterIP" }}
  selector:
    app.kubernetes.io/name: auth
  ports:
  - port: 8080
    targetPort: 8080
