{{- with .Values.ui }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  labels:
    app.kubernetes.io/component: ui
    app.kubernetes.io/name: ui
    app.kubernetes.io/part-of: greeter
spec:
  replicas: {{ .replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: ui
  template:
    metadata:
      labels:
        app.kubernetes.io/component: ui
        app.kubernetes.io/name: ui
        app.kubernetes.io/part-of: greeter
    spec:
      containers:
      - name: ui
        image: "{{ .image.repository }}:{{ .image.tag | default $.Chart.AppVersion }}"
        imagePullPolicy: {{ .image.pullPolicy }}
        {{- if .image.pullSecrets }}
        imagePullSecrets:
        {{- range .image.pullSecrets }}
        - name: {{ . }}
        {{- end }}
        {{- end }}
        {{- if and .serviceAccount.name }}
        serviceAccountName: {{ .serviceAccount.name }}
        {{- end }}
        ports:
        - containerPort: 8080
{{- end }}
