{{- with .Values.ui.ingress -}}
{{- if .enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ui-ingress
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - http:
        paths:
          {{- range .paths }}
          - path: {{ . }}
            backend:
              serviceName: ui-service
              servicePort: 8080
          {{- end }}
{{- end }}
{{- end }}
