{{- with .Values.ui }}
{{- if and .serviceAccount.create }}
{{- with .serviceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .name }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  labels:
    app.kubernetes.io/component: auth
    app.kubernetes.io/name: {{ .name }}
    app.kubernetes.io/part-of: greeter
{{- end }}
{{- end }}
{{- end }}