apiVersion: v1
kind: Service
metadata:
  name: ui-service
  labels:
    app.kubernetes.io/component: ui
    app.kubernetes.io/name: ui-service
    app.kubernetes.io/part-of: greeter
spec:
  type: {{ .Values.ui.service.type | default "ClusterIP" }}
  selector:
    app.kubernetes.io/name: ui
  ports:
  - port: 8080
    targetPort: 80
