apiVersion: apps/v1
kind: Deployment
metadata:
  name: messages
  labels:
    app.kubernetes.io/component: messages
    app.kubernetes.io/name: messages
    app.kubernetes.io/part-of: greeter
spec:
  replicas: {{ .Values.messages.replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: messages
  template:
    metadata:
      labels:
        app.kubernetes.io/component: messages
        app.kubernetes.io/name: messages
        app.kubernetes.io/part-of: greeter
    spec:
      containers:
      - name: greeter
        image: "{{ .Values.messages.image.repository }}:{{ .Values.messages.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.messages.image.pullPolicy }}
        ports:
        - containerPort: 8080
        env:
        # TODO Load this from a ConfigMap?
        - name: REDIS_DSN
          value: {{ .Values.messages.redis }}
        - name: ACCESS_TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-token-secret
              key: ACCESS_TOKEN_SECRET
        - name: REFRESH_TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-token-secret
              key: REFRESH_TOKEN_SECRET
        # TODO Load this from a ConfigMap?
        - name: DB_ADDR
          value: {{ .Values.messages.db }}
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-access-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-access-secret
              key: DB_PASSWORD
