apiVersion: apps/v1
kind: Deployment
metadata:
  name: messages
  labels:
    app.kubernetes.io/component: messages
    app.kubernetes.io/name: messages
    app.kubernetes.io/part-of: greeter
spec:
  replicas: {{ .Values.messages.replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: messages
  template:
    metadata:
      labels:
        app.kubernetes.io/component: messages
        app.kubernetes.io/name: messages
        app.kubernetes.io/part-of: greeter
    spec:
      containers:
      - name: greeter
        image: "{{ .Values.messages.image.repository }}:{{ .Values.messages.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.messages.image.pullPolicy }}
        ports:
        - containerPort: 8080
        # TODO Make this configurable together with a debug-capable image
        # Remote debug port
        - containerPort: 40000
        env:
        - name: HTTP_PORT
          value: "8080"
        - name: REDIS_ADDR
          value: {{ .Values.messages.redis.addr }}
        - name: DB_ADDR
          value: {{ .Values.messages.db.addr}}
        - name: DB_CREDS
          value: "/secrets/db/db-creds.json"
        - name: AUTH_TOKEN_CREDS
          value: "/secrets/auth/auth-token-creds.json"
        volumeMounts:
        - name: db-creds
          mountPath: "/secrets/db"
          readOnly: true
        - name: auth-token-creds
          mountPath: "/secrets/auth"
          readOnly: true
      volumes:
      - name: db-creds
        secret: {{- .Values.messages.db.secret | toYaml | nindent 10 }}
      - name: auth-token-creds
        secret: {{- .Values.messages.authToken.secret | toYaml | nindent 10 }}
