{{- with .Values.messages.ingress -}}
{{- if .enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: messages-ingress
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - http:
        paths:
          {{- range .paths }}
          - path: {{ . }}
            backend:
              service:
                name: auth-service
                port:
                  number: 8080
          {{- end }}
{{- end }}
{{- end }}
