{{- with .Values.deployment }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: messages
  labels:
    app.kubernetes.io/component: messages
    app.kubernetes.io/name: messages
#    app.kubernetes.io/part-of: greeter
spec:
  replicas: {{ .replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: messages
  template:
    metadata:
      labels:
        app.kubernetes.io/component: messages
        app.kubernetes.io/name: messages
#        app.kubernetes.io/part-of: greeter
    spec:
      {{- if and $.Values.serviceAccount.create }}
      serviceAccountName: {{ $.Values.serviceAccount.name }}
      {{- end }}
      {{- if .pullSecrets }}
      imagePullSecrets:
      {{- range .pullSecrets }}
      - name: {{ . }}
      {{- end }}
      {{- end }}
      containers:
      - name: greeter
        image: "{{ .image.repository }}:{{ .image.tag | default $.Chart.AppVersion }}"
        imagePullPolicy: {{ .image.pullPolicy }}
        ports:
        - containerPort: 8080
        # TODO Add a debug switch in the chart that will add this port and use a "debug" tag for the image
        # Remote debug port
        - containerPort: 40000
        env:
        - name: HTTP_PORT
          value: "8080"
        - name: REDIS_ENDPOINT
          value: {{ $.Values.redis.endpoint }}
        - name: DB_ENDPOINT
          value: {{ $.Values.db.endpoint}}
        {{- if .env }}
        {{- .env  | toYaml | nindent 8 }}
        {{- end }}
        {{- if .volumeMounts }}
        volumeMounts:
        {{- .volumeMounts | toYaml | nindent 8 }}
        {{- end }}
      {{- if .volumes }}
      volumes:
      {{- .volumes | toYaml | nindent 6 }}
      {{- end }}
{{- end -}}
