#!/bin/sh
image="example-services/greeter"
registry="localhost:32000"
tag="latest"
dockerFile="./Dockerfile"
platform="generic"

while [ ! -z $1 ]; do
case $1 in
    --registry) registry=$2; shift 2; continue;;
    --tag) tag=$2; shift 2; continue;;
    --debug) dockerFile=./Dockerfile.debug; shift 1; continue;;
    --platform) platform=$2; shift 2; continue;;
    *) exit 1
esac
done

target="./cmd/$platform/main.go"

if [ "$platform" = "generic" ]; then 
    suffix=""
else
    suffix="-$platform"
fi

tagLocal="$image$suffix:$tag"
tagRemote="$registry/$tagLocal"

docker build -t $tagLocal -t $tagRemote -f $dockerFile --build-arg target_arg=$target . && \
docker push $tagRemote
