#!/bin/sh

registry=localhost:32000
tag=latest
image=example-services/greeter
dockerFile=./Dockerfile

while [ ! -z $1 ]; do
case $1 in
    --registry) registry=$2; shift 2; continue;;
    --tag) tag=$2; shift 2; continue;;
    --debug) dockerFile=./Dockerfile.debug; shift 1; continue;;
    *) exit 1
esac
done

docker build -t $image:$tag -t $registry/$image:$tag -f $dockerFile . && \
docker push $registry/$image:$tag
