#
# Builder
#
FROM example-services/builder as builder

# 
# Runtime
#
FROM example-services/base-debug:latest

ENV HTTP_PORT="8080" \
    REDIS_DSN="redis:6379" \
    ACCESS_TOKEN_SECRET="secret" \
    REFRESH_TOKEN_SECRET="secret"

EXPOSE 8080
