{{- with .Values.service -}}
apiVersion: v1
kind: Service
metadata:
  name: greeter-ui-service
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app.kubernetes.io/component: greeter-ui
    app.kubernetes.io/name: greeter-ui-service
#    app.kubernetes.io/part-of: greeter
spec:
  type: {{ .type | default "ClusterIP" }}
  selector:
    app.kubernetes.io/name: greeter-ui
  ports:
  - port: 8080
    targetPort: 8080
{{- end }}