{{- if and $.Values.serviceAccount.create }}
{{- with $.Values.serviceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .name }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  labels:
    app.kubernetes.io/component: greeter-ui
    app.kubernetes.io/name: {{ .name }}
#    app.kubernetes.io/part-of: greeter
{{- end }}
{{- end }}