# Default values for greeter

messages:
  replicaCount: 1
  image:
    repository: toboregistry.azurecr.io/example-services/greeter
    pullPolicy: IfNotPresent
    tag: 1.0.0
  service:
    type: ClusterIP
  ingress:
    enabled: true
    annotations: {
      kubernetes.io/ingress.class: nginx,
      nginx.ingress.kubernetes.io/rewrite-target: /$2
      # kubernetes.io/tls-acme: "true"
    }
    paths: [
      "/greeter/messages(/|$)(.*)"
    ]
  db: ""

auth:
  replicaCount: 1
  image:
    repository: toboregistry.azurecr.io/example-services/login
    pullPolicy: IfNotPresent
    tag: 1.0.0
  service:
    type: ClusterIP
  ingress:
    enabled: true
    annotations: {
      kubernetes.io/ingress.class: nginx,
      nginx.ingress.kubernetes.io/rewrite-target: /$2
      # kubernetes.io/tls-acme: "true"
    }
    paths: [
      "/greeter/auth(/|$)(.*)"
    ]
  db: ""

ui:
  replicaCount: 1
  image:
    repository: toboregistry.azurecr.io/example-services/greeter-ui
    pullPolicy: IfNotPresent
    tag: 1.0.0
  service:
    type: ClusterIP
  ingress:
    enabled: true
    annotations: {
      kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    }
    paths: [
      "/greeter(/|$)(.*)"
    ]

# Set the shared secret all services use to handle the auth tokens created by the auth
secrets: {}
#  auth:
#    token-secret: ""
#    token-expiry: ""
#    refresh-token-secret: ""
#    refresh-token-expiry: ""
